version: 2
jobs:
  build:

    docker:
      - image: circleci/openjdk:8-jdk-browsers
    
    steps:

      - checkout

      - restore-cache:
          key: santander-parser-{{ checksum "build.gradle" }}

      - run: ./gradlew resolveDependencies
      
      - save_cache:
          paths:
            - ~/.gradle
          key: santander-parser-{{ checksum "build.gradle" }}
      
      - run: ./gradlew check
      
      - store_test_results:
          path: build/test-results/test

      - store_artifacts:
          path: build/test-results/test/*xml

      - store_artifacts:
          path: build/libs/*jar

