only-tags: &only-tags
  filters:
    tags:
      only: /^.*/

version: 2
jobs:

  build:
    docker:
      - image: circleci/openjdk:8-jdk-browsers
    
    steps:
      - checkout
      - run: ./gradlew --info --refreshDependencies clean build
      - store_test_results:
          path: build/test-results/test

  publish:
    docker:
      - image: circleci/openjdk:8-jdk-browsers
    
    steps:
      - checkout
      - run: ./gradlew --info --refreshDependencies clean publish
      - store_test_results:
          path: build/test-results/test

workflows:
  version: 2
  build:
    jobs:
      - build
  tagged-build:
    jobs:
      - publish:
          <<: *only-tags
