only-deploy-tags: &only-deploy-tags
  filters:
    tags:
      only: /^deploy-.*/
    branches:
      ignore: /.*/

version: 2
jobs:

  build:
    docker:
      - image: circleci/openjdk:8-jdk-browsers
    
    steps:
      - checkout
      - restore-cache:
          key: santander-parser-{{ checksum "build.gradle" }}
      - run: ./gradlew resolveDependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: santander-parser-{{ checksum "build.gradle" }} 
      - run: ./gradlew build
      - store_test_results:
          path: build/test-results/test
      - store_artifacts:
          path: build/libs/santander-parser-0.0.1.jar

  publish:
    docker:
      - image: circleci/openjdk:8-jdk-browsers
    
    steps:
      - run: ./gradlew publish

workflows:
  version: 2
  build:
    jobs:
      - build:
          filters:
            branches:
              only:
                - develop
                - master
                - /rc-.*/
  tagged-build:
    jobs:
      - build: *only-deploy-tags
      - publish:
          <<: *only-deploy-tags
          requires:
            - build
