only-tags: &only-tags
  filters:
    tags:
      only: /^v.*/

version: 2
jobs:

  build:
    docker:
      - image: circleci/openjdk:8-jdk-browsers
    
    steps:
      - checkout
      - restore-cache:
          key: santander-parser-{{ checksum "build.gradle" }}
      - run: ./gradlew --info resolveDependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: santander-parser-{{ checksum "build.gradle" }} 
      - run: ./gradlew --info build
      - store_test_results:
          path: build/test-results/test

  publish:
    docker:
      - image: circleci/openjdk:8-jdk-browsers
    
    steps:
      - checkout
      - restore-cache:
          key: santander-parser-{{ checksum "build.gradle" }}
      - run: ./gradlew --info resolveDependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: santander-parser-{{ checksum "build.gradle" }} 
      - run: ./gradlew --info publish
      - store_test_results:
          path: build/test-results/test

workflows:
  version: 2
  build:
    jobs:
      - build
  tagged-build:
    jobs:
      - publish:
          <<: *only-tags
