only-tags: &only-tags
  filters:
    tags:
      only: /^v.*/

version: 2
jobs:

  build:
    docker:
      - image: circleci/openjdk:8-jdk-browsers
    
    steps:
      - checkout
      - run: ./gradlew --info --refresh-dependencies clean build
      - store_test_results:
          path: build/test-results/test

  publish:
    docker:
      - image: circleci/openjdk:8-jdk-browsers
    
    steps:
      - checkout
      - run: ./gradlew --info --refresh-dependencies clean publish
      - store_test_results:
          path: build/test-results/test

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/
      - publish:
          requires:
            - build
          filters:
            tags:
              only: /v.*/

