version: 2
jobs:

  build:
    docker:
      - image: circleci/openjdk:8-jdk-browsers
    
    steps:
      - checkout
      - run:
          name: Prepare for signing
          command: scripts/prepare-for-signing.sh
      - run: ./gradlew --info --refresh-dependencies clean build
      - store_test_results:
          path: build/test-results/test

  publish-snapshot:
    docker:
      - image: circleci/openjdk:8-jdk-browsers
    
    steps:
      - checkout
      - run:
          name: Prepare for signing
          command: scripts/prepare-for-signing.sh
      - run: ./gradlew --info --refresh-dependencies clean uploadArchives
      - store_test_results:
          path: build/test-results/test

  publish-release:
    docker:
      - image: circleci/openjdk:8-jdk-browsers
    
    steps:
      - checkout
      - run:
          name: Prepare for signing
          command: scripts/prepare-for-signing.sh
      - run: ./gradlew --info --refresh-dependencies clean uploadArchives
      - run: ./gradlew --info closeAndReleaseRepository
      - store_test_results:
          path: build/test-results/test

workflows:
  version: 2
  verify:
    jobs:
      - build:
          filters:
            branches:
              ignore:
                - develop
                - release
  publish-snapshot:
    jobs:
      - build:
          filters:
            branches:
              only: develop
      - publish-snapshot:
          requires:
            - build
          filters:
            branches:
              only: develop
  publish-release:
    jobs:
      - build:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /[0-9]+(\.[0-9]+)*/
      - publish-release:
          requires:
            - build
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /[0-9]+(\.[0-9]+)*/

